import './globals.css'
import { Inter } from 'next/font/google'
// import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    {/* <script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1BCH7-dkJdURQM0vwAp8Or1IyTIB0Kdk&libraries=geometry,drawing,places">
</script> */}
<script src={`https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places&key=${process.env.GOOGLE_MAPS_API_KEY}`} async></script>
    </head>
      <body className={inter.className}>
      {/* <Header /> */}
      {children}
      </body>
    </html>
  )
}
